- name: Configure backend Server 
  hosts: backend 
  become: yes 
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 24.14.0
    ansible.builtin.command: dnf module enable nodejs:24.14.0 -y
  
  - name: Install nodejs 
    ansible.builtin.package: 
      name: nodejs
      state: present 

  - name: create expense user # here ansible modules use ansible will take of idempotency also error handling 
    ansible.builtin.user:    # using this user module here apart from underlying distribution of linux rhel /ubuntu coomand  will take care of ansible itself (yum or dnf / apt)
      name: expense          # if distribution RHEL-- useradd coomand /ubuntu--adduser this work done by ansible when u use user module 