[mysql]
mysql.jioairlines.online

[backend]
backend.jioairlines.online

[frontend]
frontend.jioairlines.online


; ansible_user=ec2-user
; ansible_password=DevOps321

; ansible_user=ec2-user
; ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem

# mysql.jioairlines.online ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/ansible.pem

[all:vars]
ansible_user=ec2-user 
ansible_ssh_private_key_file=/home/ec2-user/.ssh/id_rsa
