- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.jioairlines.online
  tasks:
    - name: ansible to install pymysql
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: install MySQL Server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: start mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    
    - name: connect mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
      ignore_errors: true
      register: mysql_info

    - name: print mysql info
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"

    - name: setup MySQL root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
      when: mysql_info.failed is true


##### NOTES FOR MYSQL SERVER #######################
# when condition is here 

# mysql_root_password: ExpenseApp@1
# login_user: root
# login_password: ExpenseApp@1
# login_host: mysql.jioairlines.online   # or the IP if DNS isn’t ready


# once connected to mysql server  throguh ssh -i "id_rsa" ec2-user@ec2-44-222-222-95.compute-1.amazonaws.com then
# mysql -h mysql.jioairlines.online -u root -p   other wise  without connection direct ssh ec2-user@mysql.jioairlines.online mysql -u root -p

# it doesnt workout with above credentials then go for with pvt ip address

# mysql -h 172.31.7.207 -u root -p

# Your Ansible credentials are: root / ExpenseApp@1
